
# $terminal = uwsm-app -- $TERMINAL
$terminal = uwsm-app -- kitty
#$browser = omarchy-launch-browser
$browser = uwsm app -- brave --new-window --ozone-platform=wayland
bind = SUPER, Q, killactive
bind = SUPER, Return, exec, kitty
bindd = SUPER ,E, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser , exec, $brave
bindd = SUPER SHIFT, B, Browser , exec, brave
bindd = SUPER SHIFT ALT, B, Browser (private), exec, $browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT ALT, N, Editor, exec, omarchy-launch-editor
bindd= SUPER SHIFT ,C,VSCode,exec,code
# bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian --disable-gpu --enable-wayland-ime"
bindd = CTRL ALT, T, Terminal, exec,kitty
bindd=SUPER,L,Lock screen,exec,hyprlock



#WEB app
## If your web app url contains #, type it as ## to prevent hyperland treat it as comments


bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT,G,Gemini,exec,omarchy-launch-webapp "https://gemini.google.com/"
bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, Y, YouTube, exec, brave --new-window "https://youtube.com/"
bindd = SUPER SHIFT,N, Notion, exec,omarchy-launch-webapp "https://notion.so/"
bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"


# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-launch-browser


unbind = , PRINT
unbind = SHIFT, PRINT
unbind = CTRL, PRINT
unbind = ALT, PRINT
unbind = CTRL ALT, PRINT
unbind = SUPER, PRINT
unbind = SUPER ALT, S, killactive
# Screenshots and Recordings with SUPER + LBRACKET ([)
bindd = SUPER, LBRACKET, Screenshot of region, exec, ~/.local/share/omarchy/bin/omarchy-cmd-screenshot
bindd = SUPER SHIFT, S, Screenshot of window, exec, ~/.local/share/omarchy/bin/omarchy-cmd-screenshot window
#bindd = SUPER CTRL, LBRACKET, Screenshot of display, exec, ~/.local/share/omarchy/bin/omarchy-cmd-screenshot output
bindd = SUPER ALT, S, Screen record a region, exec, ~/.local/share/omarchy/bin/omarchy-cmd-screenrecord
#bindd = SUPER CTRL ALT, LBRACKET, Screen record display, exec, ~/.local/share/omarchy/bin/omarchy-cmd-screenrecord output

# Color picker moved to a dedicated, non-conflicting key
bindd = SUPER SHIFT, P, Color picker, exec, pkill hyprpicker || hyprpicker -a

# Hide / Show windows
bindd = SUPER, H, Hide active, movetoworkspacesilent, special:hidden
bindd = SUPER SHIFT, H, Show hidden, togglespecialworkspace, hidden
# When in hidden workspace, press SUPER+SHIFT+H again to close it, or click a window to restore it

# Unbind default brightness controls
unbind = ,XF86MonBrightnessUp
unbind = ,XF86MonBrightnessDown

# Bind ultra-low brightness controls
bindeld = ,XF86MonBrightnessUp, Logarithmic brightness up, exec, ~/.local/bin/brightness-control up
bindeld = ,XF86MonBrightnessDown, Logarithmic brightness down, exec, ~/.local/bin/brightness-control down
