# Hyprland look and feel overrides (optional)
decoration {
    rounding = 10
       # Opacity settings
    active_opacity = 0.8
    inactive_opacity = 0.6

    blur {
        enabled = true
        size = 2        # How big the blur is (e.g., 3, 8, 10)
        passes = 3       # How many times to blur (e.g., 1, 2, 3)
        # -- Optional settings to control the "feel" ---
        # More performance-friendly blur (may look different)
        new_optimizations = true
        # Ignores window opacity, blurs at full strength
        ignore_opacity = true 
        # How much noise to add (0.0 - 1.0)
        noise = 0
        # Contrast modulation (0.0 - 2.0)
        contrast = 1.0
        # Brightness modulation (0.0 - 2.0)
        brightness = 0.7
        # Inease saturation of blurred colors (0.0 - 1.0)
        vibrancy = 0.1696 
        popups = true
    }
}

xwayland {
    enabled = true
}

# # SwayNC
# layerrule = ignorezero, swaync-control-center
# layerrule = ignorezero, swaync-notification-window
# layerrule = ignorealpha 0.5, swaync-control-center
# layerrule = ignorealpha 0.5, swaync-notification-window

# # Walker
# layerrule = blur, walker
# layerrule = dimaround, walker



# Add any other personal Hyprland configuration below
#windowrule = match:class qemu, workspace 5
windowrule = match:class ^(brave-web\.whatsapp\.com__-Default)$, float 1
windowrule = match:class ^(brave-web\.whatsapp\.com__-Default)$, center 1
windowrule = match:class ^(brave-web\.whatsapp\.com__-Default)$, size 900 700
windowrule = match:class ^(brave-web\.whatsapp\.com__-Default)$, pin 1

# Network Login Popup
windowrule = match:class ^(brave-172\.16\.73\.12__httpclient\.html-Default)$, workspace special:netlogin
windowrule = match:class ^(brave-172\.16\.73\.12__httpclient\.html-Default)$, float 1
windowrule = match:class ^(brave-172\.16\.73\.12__httpclient\.html-Default)$, center 1
windowrule = match:class ^(brave-172\.16\.73\.12__httpclient\.html-Default)$, size 350 500

# 1. Float the window while it is still loading ("Untitled")
windowrule = match:class ^(brave-browser)$, match:title ^(Untitled - Brave)$, float 1
windowrule = match:class ^(brave-browser)$, match:title ^(Untitled - Brave)$, center 1
windowrule = match:class ^(brave-browser)$, match:title ^(Untitled - Brave)$, size 500 700

# 2. Keep it floating when the title updates to "Sign in..."
windowrule = match:title ^(Sign in - Google Accounts - Brave)$, float 1
windowrule = match:title ^(Sign in - Google Accounts - Brave)$, center 1
windowrule = match:title ^(Sign in - Google Accounts - Brave)$, size 500 700

# 3. Force normal "New Tab" windows back to tiling if they floated by accident
windowrule = match:class ^(brave-browser)$, match:title ^(New Tab - Brave)$, tile 1