# Hyprland look and feel overrides (optional)
decoration {
    rounding = 10
    blur {
        enabled = true
        size = 2        # How big the blur is (e.g., 3, 8, 10)
        passes = 3       # How many times to blur (e.g., 1, 2, 3)
        # -- Optional settings to control the "feel" ---
        # More performance-friendly blur (may look different)
        new_optimizations = true
        # Ignores window opacity, blurs at full strength
        ignore_opacity = true 
        # How much noise to add (0.0 - 1.0)
        noise = 0.8
        # Contrast modulation (0.0 - 2.0)
        contrast = 1.0
        # Brightness modulation (0.0 - 2.0)
        brightness = 0.7
        # Inease saturation of blurred colors (0.0 - 1.0)
        vibrancy = 0.1696 
        popups = true
    }
}

xwayland {
    enabled = true
}

layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window
#layerrule = blur, walker
layerrule = dimaround, walker



# Add any other personal Hyprland configuration below
#windowrule = workspace 5, class:qemu
windowrulev2 = float,class:^(brave-web\.whatsapp\.com__-Default)$
windowrulev2 = center,class:^(brave-web\.whatsapp\.com__-Default)$
windowrulev2 = size 900 700,class:^(brave-web\.whatsapp\.com__-Default)$
windowrulev2 = pin,class:^(brave-web\.whatsapp\.com__-Default)$

# Network Login Popup
windowrulev2 = workspace special:netlogin,class:^(brave-172\.16\.73\.12__httpclient\.html-Default)$
windowrulev2 = float,class:^(brave-172\.16\.73\.12__httpclient\.html-Default)$
windowrulev2 = center,class:^(brave-172\.16\.73\.12__httpclient\.html-Default)$
windowrulev2 = size 350 500,class:^(brave-172\.16\.73\.12__httpclient\.html-Default)$

# 1. Float the window while it is still loading ("Untitled")
windowrulev2 = float, class:^(brave-browser)$, title:^(Untitled - Brave)$
windowrulev2 = center, class:^(brave-browser)$, title:^(Untitled - Brave)$
windowrulev2 = size 500 700, class:^(brave-browser)$, title:^(Untitled - Brave)$

# 2. Keep it floating when the title updates to "Sign in..."
windowrulev2 = float, title:^(Sign in - Google Accounts - Brave)$
windowrulev2 = center, title:^(Sign in - Google Accounts - Brave)$
windowrulev2 = size 500 700, title:^(Sign in - Google Accounts - Brave)$
# 3. Force normal "New Tab" windows back to tiling if they floated by accident
windowrulev2 = tile, class:^(brave-browser)$, title:^(New Tab - Brave)$

