workspace = special:scratchpad, on-created-empty:exec kitty --class kitty-scratchpad

windowrule = match:class ^(kitty-scratchpad)$, float on
windowrule = match:class ^(kitty-scratchpad)$, size 900 700
windowrule = match:class ^(kitty-scratchpad)$, center on
windowrule = match:class ^(kitty-scratchpad)$, border_size 0
windowrule = match:class ^(kitty-scratchpad)$, opacity 0.75
# windowrule = match:class ^(kitty-scratchpad)$, noblur on
windowrule = match:class ^(kitty-scratchpad)$, animation slide
windowrule = match:class ^(kitty-scratchpad)$, workspace special:scratchpad silent
windowrule = match:class ^(kitty-scratchpad)$, rounding 20

bind = SUPER SHIFT, RETURN, togglespecialworkspace, scratchpad

# gesture
# gesture = 4, vertical, special, scratchpad

# Animation for gesture 
animation = specialWorkspace, 1, 2, default, slide top