# Background and foreground colors
background = #091326
foreground = #f5f8fc

# Standard colors
palette = 0=#091326
palette = 1=#989790
palette = 2=#79A7E0
palette = 3=#7BA4D2
palette = 4=#749be1
palette = 5=#70a0f5
palette = 6=#6E98CC
palette = 7=#B0C6E6

# Bright colors
palette = 8=#667fae
palette = 9=#c4c4bf
palette = 10=#c1d8f4
palette = 11=#bdd3eb
palette = 12=#bdd1f4
palette = 13=#c3d8fe
palette = 14=#afc8e6
palette = 15=#f5f8fc
