$color = rgba(9, 19, 38, 1)
$inner_color = rgba(9, 19, 38, 0.66)
$outer_color = rgba(112, 160, 245, 1)
$font_color = rgba(245, 248, 252, 1)
$placeholder_color = rgba(245, 248, 252, 0.7)
$check_color = rgba(110, 152, 204, 1)
