background            #091326
foreground            #f5f8fc

# black
color0  #091326
color8  #667fae

# red
color1  #989790
color9  #c4c4bf

# green
color2  #79A7E0
color10 #c1d8f4

# yellow
color3  #7BA4D2
color11 #bdd3eb

# blue
color4  #749be1
color12 #bdd1f4

# magenta
color5  #70a0f5
color13 #c3d8fe

#cyan
color6  #6E98CC
color14 #afc8e6

#white
color7  #B0C6E6
color15 #f5f8fc


